version: 0.2
            
phases:
  install:   
    runtime-versions:
      java: openjdk8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre-build
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - target/Java-AWS-deploy-0.0.1-SNAPSHOT.jar